[package]
name = "rssg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0"
atom_syndication = "0.11"
clap = { version = "3.1.18", features = ["derive"] }
